### ISSUE TITLE
Pls. Explain

### ISSUE THREAD

**Issue by GurprasadSingh** [Yagwar/ASAG_Test#1]
Hi , I am also working on a similar project. Can you pls. Explain this project to me , what approach should I follow to devlop a grading system from scratch?

**Comment by Yagwar** [comment]
Hi!
Sorry for my late response.
In writing an paper about this project, so you can find more detail later. The approach is a supervised learning problem, basically text classification. This is one of my first ML projects, and because of that I use basics techniques. Preprocessing is frequentist, with Bags Of Words embeddings. Algorithms are shallow classifiers, SVM, Assemble trees...
Results are comparison of F1 as performance metrics for classification. 
Thatas basically the project.
Best!

**Comment by Yagwar** [comment]
Dataset, baseline methods, performance metrics and others clasifiers comes from this paper: https://link.springer.com/article/10.1007/s40593-014-0026-8

**Comment by GurprasadSingh** [comment]
Oh thank you so much for your response. I will do give your paper a read and get back to you in case of any queries. 

Thanks and Regards
Gurprasad Singh
